version: '3.8'

services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb-container
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 12345678  # 루트 비밀번호
      MARIADB_DATABASE: sangahnCloud      # 초기 생성할 데이터베이스
      MARIADB_USER: sangahn               # 사용자 이름
      MARIADB_PASSWORD: sangahn@#         # 사용자 비밀번호
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  mariadb_data:
