spring:
  application:
    name: sangahnCloudBoot

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/sangahnCloud
    username: sangahn
    password: sangahn@#

    hikari:
      minimum-idle: 3
      maximum-pool-size: 5
      connection-timeout: 10000
      idle-timeout: 300000
      max-lifetime: 1800000
      leak-detection-threshold: 2000

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true

    properties:
      hibernate:
        default_batch_fetch_size: 10
        format_sql: true

  logging:
    level:
      org.springframework.security.web: TRACE
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

org:
  sangahn:
    accessTime: 60
    refreshTime: 216000
    alwaysNew: true
    upload:
      path: upload